### ISSUE TITLE
runserverが立ち上がらないよ

### ISSUE THREAD

**Issue by Teriter** [kaito1002/OyoQuiz#9]
新しくanswerとjudgeファイル作ったけどエラーが出てサーバーが立てられなくなった。対応を頼む。

**Comment by kaito1002** [comment]
view書かないとそりゃ動かんよ

**Comment by Teriter** [comment]
views.pyのことです?

**Comment by kaito1002** [comment]
view書いといたから動くようになったよ
あと, contextがうまく使えてないみたいだったから

- exercise.html
- answer.html
- judge.html

を直しといたよ
各ページも繋がるようになってるから参考に書き方覚えてね
